<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SFawgY.' shared service.

return $this->privates['.service_locator.SFawgY.'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('account' => function (): \App\Entity\Account {
    return ($this->privates['.errored..service_locator.SFawgY..App\Entity\Account'] ?? $this->load('getAccount2Service.php'));
}));
