<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccountController::add' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController::create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\AccountController::delete' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController::edit' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController::list' => function () {
    return ($this->privates['.service_locator.Wv_TX7a'] ?? $this->load('get_ServiceLocator_WvTX7aService.php'));
}, 'App\\Controller\\AccountController::supp' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController::view' => function () {
    return ($this->privates['.service_locator.SFawgY.'] ?? $this->load('get_ServiceLocator_SFawgY_Service.php'));
}, 'App\\Controller\\TransactionController::create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\TransactionController::delete' => function () {
    return ($this->privates['.service_locator.m3hBeYH'] ?? $this->load('get_ServiceLocator_M3hBeYHService.php'));
}, 'App\\Controller\\TransactionController::list' => function () {
    return ($this->privates['.service_locator.KQ0rQ_v'] ?? $this->load('get_ServiceLocator_KQ0rQVService.php'));
}, 'App\\Controller\\AccountController:add' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController:create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\AccountController:delete' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController:edit' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController:list' => function () {
    return ($this->privates['.service_locator.Wv_TX7a'] ?? $this->load('get_ServiceLocator_WvTX7aService.php'));
}, 'App\\Controller\\AccountController:supp' => function () {
    return ($this->privates['.service_locator.COVRCGO'] ?? $this->load('get_ServiceLocator_COVRCGOService.php'));
}, 'App\\Controller\\AccountController:view' => function () {
    return ($this->privates['.service_locator.SFawgY.'] ?? $this->load('get_ServiceLocator_SFawgY_Service.php'));
}, 'App\\Controller\\TransactionController:create' => function () {
    return ($this->privates['.service_locator.v_q6gfB'] ?? $this->load('get_ServiceLocator_VQ6gfBService.php'));
}, 'App\\Controller\\TransactionController:delete' => function () {
    return ($this->privates['.service_locator.m3hBeYH'] ?? $this->load('get_ServiceLocator_M3hBeYHService.php'));
}, 'App\\Controller\\TransactionController:list' => function () {
    return ($this->privates['.service_locator.KQ0rQ_v'] ?? $this->load('get_ServiceLocator_KQ0rQVService.php'));
})));
