<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDNdaLWc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDNdaLWc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDNdaLWc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDNdaLWc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDNdaLWc\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DNdaLWc',
    'container.build_id' => '546e48c2',
    'container.build_time' => 1539592390,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDNdaLWc');
