<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSVCMNyI\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSVCMNyI/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSVCMNyI.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSVCMNyI\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSVCMNyI\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'SVCMNyI',
    'container.build_id' => '7724a663',
    'container.build_time' => 1539610519,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSVCMNyI');
